{% set name = "geoarrow-c" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geoarrow-c-{{ version }}.tar.gz
  sha256: 71ca8e779214769d8ddd28348a96a26ebe43203ba9a9c578e55d6bdab7494381

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=61.0.0
    - setuptools-scm
    - cython
    - pip
  run:
    - python

test:
  imports:
    - geoarrow.c
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geoarrow/geoarrow-c
  summary: Low-level Python bindings to the GeoArrow C implementation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - paleolimbot
